feat(Folder) #MAG-286 : handle share folders in back
OPEN-ENT-NG/magneto pull request #102
Opened 2024-01-17 16:05 UTC by Rseuret

## Describe your changes

Handle share for folders 

## Checklist tests
Check if a right is apply to all the folder s children
Check if the old rights are still saved with the new rights applied 

## Issue ticket number and link
https://jira.support-ent.fr/browse/MAG-286

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-01-17 16:54 UTC, alicedraillard approved these changes

2024-01-17 17:24 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/controller/ShareController.java
> +    @Put("/:type/share/resource/:id")
Pense à mettre à jour les docs d'API

2024-01-17 17:24 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/service/FolderService.java
> +        Future<Void> shareFolder(String id, List<SharedElem> newShares, List<SharedElem> deletedShares);
Si possible, tu peux ajouter une description pour les paramètres.

2024-01-17 17:24 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
> +                    String message = String.format("[Magneto@%s::getAllBoardsIds] Failed to recovers boards and folders ids",
getChildrenBoardsIds dans le log

2024-01-17 17:24 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
> +                List<SharedElem> sharedElems = getOldRights( success.getJsonArray("shared", new JsonArray()), newShare);
Field.SHARED

2024-01-17 17:24 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
> +                String message = String.format("[Magneto@%s::updateOldFolder] Failed to update old folder",
getOldDataToUpdate dans le log

2024-01-18 08:51 UTC, flmartineau approved these changes

2024-01-18 08:51 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/controller/ShareController.java
> +                                                params, true);
C'est quoi ce "test" ?

2024-01-18 08:51 UTC, flmartineau commented on src/main/java/fr/cgi/magneto/controller/ShareController.java
> +                                                    params, true);
pareil ici ?

2024-01-18 08:52 UTC, FlorentMr requested changes

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/controller/ShareController.java
> +        this.folderService.getFolderByBoardId(id).onSuccess(s -> {
Manque un onFailure

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/controller/ShareController.java
> +                .onSuccess(checkRight -> {
Manque un onFailure

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/service/impl/DefaultCardService.java
> -                        //TODO BIEN CHECK SI CA MARCHE une fois MAG-286 implentée
Alors ça marche? (faut le laisser pour plus tard ou commentaire à enlever?)

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
> +        List<SharedElem>  oldSharedElems= getSharedElemList(oldShared);
ça me trigger trop dsl mais ya un espace en trop

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
> +        List<SharedElem>  oldSharedElems= getSharedElemList(oldShared);
là en a un en trop et un oublié pour le =

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
> +    public  List<SharedElem> getOldRights(List<SharedElem> oldSharedElems, List<SharedElem> newSharedElems) {
espace en troooooop

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/service/impl/DefaultShareService.java
> +        this.getOldDataToUpdate(id, collection).onSuccess(folder -> {
manque un onFailure

2024-01-18 08:52 UTC, FlorentMr commented on src/main/java/fr/cgi/magneto/service/ServiceFactory.java
> +        return new DefaultShareService( mongoDb);
espace

2024-01-18 10:32 UTC, FlorentMr approved these changes

2024-01-18 15:08 UTC, alicedraillard approved these changes

2024-01-18 15:08 UTC, alicedraillard commented on src/main/java/fr/cgi/magneto/Magneto.java
> +		ServiceFactory serviceFactory = new ServiceFactory(vertx, storage, magnetoConfig, Neo4j.getInstance(), Sql.getInstance(), MongoDb.getInstance() ,securedActions);
espace apres la virgule pas avant

2024-01-18 15:08 UTC, alicedraillard commented on src/main/java/fr/cgi/magneto/service/impl/DefaultFolderService.java
> +    public  Future<JsonObject> getFolderByBoardId(String boardId){
espace avant le {

2024-01-18 15:18 UTC, merged