feat(react): #MAG-388 change router type to work in production mode
OPEN-ENT-NG/magneto pull request #175
Opened 2024-04-02 08:43 UTC by FlorentMr

## Describe your changes
change router type to work in production mode

## Checklist tests
Check all different routes and check if the backend (with the API) is working.
The new routes are [http://localhost:4200/board/{id}/view](http://localhost:4200/board/%7Bid%7D/view) and [http://localhost:4200/board/{id}/reading](http://localhost:4200/board/%7Bid%7D/reading)

## Issue ticket number and link
[MAG-389](https://jira.support-ent.fr/browse/MAG-389)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-04-02 09:09 UTC, JinDouang requested changes

2024-04-02 09:09 UTC, JinDouang commented on frontend/src/routes/index.tsx
> +  basename: import.meta.env.PROD ? "" : "/",
du coup aucun impact si on enlève le /magneto ?

d'un point de vue local et déploiement ng2 etc

qu'est-ce que ça change avoir un "" ou "/" ?

2024-04-02 09:09 UTC, JinDouang commented on build.sh
> +sudo rm -rf ../frontend/dist
pas de sudo

2024-04-02 09:09 UTC, JinDouang commented on build.sh
> +sudo chmod -R 777 build.sh
pas nécessaire de faire le chmod

il faut éviter même

ca peut avoir des conséquences sur notre jenkins et/ou jenkins edifice

2024-04-02 09:09 UTC, JinDouang commented on backend/src/main/java/fr/cgi/magneto/controller/MagnetoController.java
> +        renderView(request, param, "index.html", null);
tu peux nous expliquer pourquoi tu le renommes en index.html ?

2024-04-02 09:09 UTC, JinDouang commented on frontend/build.sh
> +  echo "2"
enlever les messages avec `echo`

2024-04-02 15:34 UTC, JinDouang commented on frontend/src/routes/index.tsx
> +  basename: import.meta.env.PROD ? "" : "/",
Mais dans ce cas, on pourrait ne pas avoir de basename tout court ?

2024-04-02 15:39 UTC, FlorentMr commented on frontend/src/routes/index.tsx
> +  basename: import.meta.env.PROD ? "" : "/",
Je sais pas pourquoi ne pas avoir de basename posait problème la dernière fois, mais effectivement ici le basename a bien l'air inutile, je vérifie sur NG2 malgré tout et je valide le changement

2024-04-04 15:35 UTC, FlorentMr commented on frontend/build.sh
> +  export USER_UID=0
Je confirme qu'on a plus besoin du basename, c'est corrigé

2024-04-05 08:50 UTC, merged