feat(toaster) : #MAG-355 adds toaster for folders and boards
OPEN-ENT-NG/magneto pull request #184
Opened 2024-06-12 13:11 UTC by FlorentMr

## Describe your changes
Adds a toaster for folders and boards, with all its functional modals.

## Checklist tests
Check if the toaster is working the same as the one in 1.8 version. 
Test rights of different users.

## Issue ticket number and link
[MAG-355](https://jira.support-ent.fr/browse/MAG-355)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-06-17 13:00 UTC, alicedraillard commented on frontend/src/components/content-page/ContentPage.tsx
fichier utile ?

2024-06-17 13:02 UTC, alicedraillard commented on frontend/src/hooks/useActionsDefinitions.ts
fichier utile ??

2024-06-18 14:26 UTC, Mattox0 commented on frontend/src/components/board-list/BoardList.tsx
> +    console.log(boardData);
console.log à enlever ?

2024-06-18 14:26 UTC, Mattox0 commented on frontend/src/components/create-folder/CreateFolder.tsx
> +      console.log("Dossier " + title + " créé!");
console.log a enlever ?

2024-06-18 14:27 UTC, JinDouang commented on frontend/src/components/create-folder/CreateFolder.tsx
> +      console.log("Dossier " + title + " créé!");
pense à retirer les console log

2024-06-18 14:28 UTC, JinDouang commented on frontend/src/components/create-folder/CreateFolder.tsx
> +    if (folderToUpdate != null) {
tu as un risque d'erreur asynchrone sans catch

à (re)qualifier ce que tu fais dans ton code en cas d'erreur sur ton await updateFolder ou addFolder

2024-06-18 14:28 UTC, Mattox0 commented on frontend/src/components/toaster-container/ToasterContainer.tsx
> +    console.log(currentFolder.id == FOLDER_TYPE.DELETED_BOARDS);
console.log a enlever ?

2024-06-18 14:29 UTC, Mattox0 commented on frontend/src/components/toaster-container/ToasterContainer.tsx
> +                      Ne plus partager à toute la plateforme
i18n peut etre ?

2024-06-18 14:29 UTC, Mattox0 commented on frontend/src/hooks/usePredefinedToasts.ts
> +      console.log("success")
console.log a enlever ?

2024-06-18 14:31 UTC, Mattox0 approved these changes

2024-06-18 14:32 UTC, JinDouang commented on frontend/src/components/create-tab/createTab.tsx
> +    if (boardToUpdate == null) {
il peut undefined également, il faut vérifier ça

2024-06-18 14:32 UTC, JinDouang commented on frontend/src/components/create-tab/createTab.tsx
> +    if (boardToUpdate != null) {
il peut undefined également, il faut vérifier ça

2024-06-18 14:36 UTC, JinDouang commented on frontend/src/components/move-board/MoveBoard.tsx
> +    console.log("loading");
pas pertinent de juste mettre les console.log pour les erreurs

2024-06-18 14:40 UTC, JinDouang commented on frontend/src/hooks/usePredefinedToasts.ts
> +      console.log("success")
log à enlever

2024-06-18 14:41 UTC, JinDouang commented on frontend/src/hooks/useRestoreBoardsAndFolders.ts
> +        failureMessage: t("Un problème est survenu, tableau(x) non restauré(s) :("),
traduction ?

2024-06-18 14:55 UTC, FlorentMr commented on frontend/src/components/create-tab/createTab.tsx
> +    if (boardToUpdate != null) {
Le check "!=" vérifie et le fait qu'il soit null et le fait qu'il soit undefined, donc rien n'est omis ici (par contre si c'était un "!==", là je checkerais pas le undefined en effet)
source : https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-and-non-undefined-type-guards

2024-06-18 15:52 UTC, JinDouang requested changes

2024-06-18 15:52 UTC, JinDouang commented on frontend/src/components/create-tab/createTab.tsx
> +import React, { FunctionComponent, useEffect, useState } from "react";
createTab, mais si on parle de board, à revoir pour avoir un nommage précis
(de plus, c du fr)

2024-06-18 15:52 UTC, JinDouang commented on frontend/src/components/delete-modal/DeleteModal.tsx
> +      preDeleteBoardsAndToast();
peut-être pour chaque methode, faire des try catch avec un await pour maitriser le comportement asynchrone

2024-06-18 15:52 UTC, JinDouang commented on frontend/src/components/toaster-container/ToasterContainer.tsx
> +    console.log(currentFolder);
console.log à enlever

2024-06-18 15:52 UTC, JinDouang commented on frontend/src/components/toaster-container/ToasterContainer.tsx
> +export const ToasterContainer = ({
Peux-tu éclaircir un peu plus sur l'usage du toaster ? y a bcp de logique dessus 
(screen si possible)

Si c'est la barre orange en bas avec les choix de partage/suppression de ressource etc... faudrait :
- en faire une feature dédiée
- renommer le nom (je vois que tu as le actionbarcontainer ..?)

2024-06-19 07:20 UTC, FlorentMr commented on frontend/src/components/toaster-container/ToasterContainer.tsx
> +export const ToasterContainer = ({
Yep c'est bien la barre orange en bas. J'ai séparé pas mal de logique et j'ai gardé ce qui servait à la gestion de droit et de condition pour l'affichage ou non des boutons. Tu veux dire quoi par en faire une feature dédiée? Séparer le visuel + son animation de la logique des boutons?

2024-06-19 07:39 UTC, FlorentMr commented on frontend/src/hooks/useRestoreBoardsAndFolders.ts
> +        if (boardIds.length > 0) {
Il y a déjà un try catch dans le hook qui contient ces deux actions, donc les erreurs sont déjà gérées

2024-06-20 12:03 UTC, FlorentMr commented on frontend/src/components/toaster-container/ToasterContainer.tsx
> +export const ToasterContainer = ({
On est bien sur un toaster du même nom que dans Magneto Angular, donc no souc à ce niveau!

2024-06-20 12:51 UTC, JinDouang approved these changes

2024-06-20 12:53 UTC, merged