feat(lock): add lock magnet feature and right control
OPEN-ENT-NG/magneto pull request #326
Opened 2024-11-12 16:18 UTC by alicedraillard

## Describe your changes

## Checklist tests

## Issue ticket number and link
[MAG-513](https://jira.support-ent.fr/browse/MAG-513)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-11-12 17:05 UTC, FlorentMr requested changes

2024-11-12 17:05 UTC, FlorentMr commented on frontend/src/components/board-card/BoardCard.tsx
> +        (!card.locked && (isCardOwner || hasManageRights() || hasEditRights()))
Si hasEditRights() est true, hasManageRights() l'est forcément aussi, donc ya moyen de réduire tout ça, probablement un truc du style "isCardOwner && (card.locked ? hasManageRights() : hasEditRights())"

2024-11-13 08:36 UTC, Mattox0 approved these changes

2024-11-13 13:42 UTC, FlorentMr approved these changes

2024-11-13 13:44 UTC, merged